language: node_js
node_js:
  - "stable"

sudo: false

cache:
  directories:
    - node_modules
    - jspm_packages

branches:
  only:
    - master

install:
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - node_modules/.bin/jspm install

script:
  - gulp build
  - gulp test
